const hasTextEncoder = typeof TextEncoder !== "undefined";
const hasTextDecoder = typeof TextDecoder !== "undefined";

export function deflateStringToQueryParam(input = "") {
  const text = String(input ?? "");
  try {
    const bytes = stringToUtf8Bytes(text);
    const compressed = zlibDeflateStored(bytes);
    return encodeURIComponent(bytesToBinaryBase64(compressed));
  } catch (error) {
    console.warn("Failed to compress playground payload, falling back to raw URI encoding:", error);
    return encodeURIComponent(text);
  }
}

export function inflateStringFromQueryParam(input = "") {
  if (!input) return "";
  try {
    const compressed = binaryBase64ToBytes(decodeURIComponent(input));
    return utf8BytesToString(inflateZlibOrRaw(compressed));
  } catch (error) {
    try {
      return decodeURIComponent(input);
    } catch {
      return String(input);
    }
  }
}

function stringToUtf8Bytes(text) {
  if (hasTextEncoder) return new TextEncoder().encode(text);
  const encoded = unescape(encodeURIComponent(text));
  const bytes = new Uint8Array(encoded.length);
  for (let i = 0; i < encoded.length; i += 1) bytes[i] = encoded.charCodeAt(i);
  return bytes;
}

function utf8BytesToString(bytes) {
  if (hasTextDecoder) return new TextDecoder().decode(bytes);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return decodeURIComponent(escape(binary));
}

function bytesToBinaryBase64(bytes) {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function binaryBase64ToBytes(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function zlibDeflateStored(input) {
  const data = input instanceof Uint8Array ? input : new Uint8Array(input);
  const raw = deflateRawStored(data);
  const output = new Uint8Array(raw.length + 6);
  // zlib header: CMF=0x78 (deflate, 32K window), FLG=0x01 (fastest/no compression).
  output[0] = 0x78;
  output[1] = 0x01;
  output.set(raw, 2);
  const checksum = adler32(data);
  output[output.length - 4] = (checksum >>> 24) & 0xff;
  output[output.length - 3] = (checksum >>> 16) & 0xff;
  output[output.length - 2] = (checksum >>> 8) & 0xff;
  output[output.length - 1] = checksum & 0xff;
  return output;
}

function inflateZlibOrRaw(input) {
  const data = input instanceof Uint8Array ? input : new Uint8Array(input);
  if (data.length >= 6 && (data[0] & 0x0f) === 8 && (((data[0] << 8) + data[1]) % 31) === 0) {
    const raw = data.slice(2, -4);
    const output = inflateRawStored(raw);
    const expected = (
      (data[data.length - 4] << 24) |
      (data[data.length - 3] << 16) |
      (data[data.length - 2] << 8) |
      data[data.length - 1]
    ) >>> 0;
    const actual = adler32(output);
    if (expected !== actual) {
      throw new Error("Invalid zlib checksum for playground payload");
    }
    return output;
  }
  // Backward compatibility for links generated by the earlier local raw-deflate implementation.
  return inflateRawStored(data);
}

function adler32(input) {
  const data = input instanceof Uint8Array ? input : new Uint8Array(input);
  let a = 1;
  let b = 0;
  for (const byte of data) {
    a = (a + byte) % 65521;
    b = (b + a) % 65521;
  }
  return (((b << 16) | a) >>> 0);
}

function deflateRawStored(input) {
  const data = input instanceof Uint8Array ? input : new Uint8Array(input);
  const state = new BitWriter();
  let offset = 0;
  while (offset < data.length) {
    const blockLength = Math.min(65535, data.length - offset);
    const isFinal = offset + blockLength >= data.length;
    state.writeBits(isFinal ? 1 : 0, 1);
    state.writeBits(0, 2);
    state.alignToByte();
    state.writeByte(blockLength & 0xff);
    state.writeByte((blockLength >>> 8) & 0xff);
    const nlen = (~blockLength) & 0xffff;
    state.writeByte(nlen & 0xff);
    state.writeByte((nlen >>> 8) & 0xff);
    for (let i = 0; i < blockLength; i += 1) {
      state.writeByte(data[offset + i]);
    }
    offset += blockLength;
  }
  if (data.length === 0) {
    state.writeBits(1, 1);
    state.writeBits(0, 2);
    state.alignToByte();
    state.writeByte(0);
    state.writeByte(0);
    state.writeByte(0xff);
    state.writeByte(0xff);
  }
  return state.toUint8Array();
}

function inflateRawStored(input) {
  const reader = new BitReader(input);
  const chunks = [];
  let totalLength = 0;
  let finalBlock = false;

  while (!finalBlock) {
    finalBlock = reader.readBits(1) === 1;
    const blockType = reader.readBits(2);
    if (blockType !== 0) {
      throw new Error("Unsupported compressed playground block type");
    }
    reader.alignToByte();
    const len = reader.readByte() | (reader.readByte() << 8);
    const nlen = reader.readByte() | (reader.readByte() << 8);
    if (((len ^ 0xffff) & 0xffff) !== nlen) {
      throw new Error("Invalid compressed playground block length");
    }
    const chunk = reader.readBytes(len);
    chunks.push(chunk);
    totalLength += chunk.length;
  }

  const output = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    output.set(chunk, offset);
    offset += chunk.length;
  }
  return output;
}

class BitWriter {
  constructor() {
    this.bytes = [];
    this.bitBuffer = 0;
    this.bitCount = 0;
  }

  writeBits(value, count) {
    let remaining = count;
    let current = value;
    while (remaining > 0) {
      this.bitBuffer |= (current & 1) << this.bitCount;
      this.bitCount += 1;
      current >>>= 1;
      remaining -= 1;
      if (this.bitCount === 8) {
        this.flushByte();
      }
    }
  }

  alignToByte() {
    if (this.bitCount > 0) this.flushByte();
  }

  writeByte(byte) {
    if (this.bitCount === 0) {
      this.bytes.push(byte & 0xff);
    } else {
      this.writeBits(byte & 0xff, 8);
    }
  }

  flushByte() {
    this.bytes.push(this.bitBuffer & 0xff);
    this.bitBuffer = 0;
    this.bitCount = 0;
  }

  toUint8Array() {
    this.alignToByte();
    return new Uint8Array(this.bytes);
  }
}

class BitReader {
  constructor(bytes) {
    this.bytes = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
    this.byteIndex = 0;
    this.bitBuffer = 0;
    this.bitCount = 0;
  }

  readBits(count) {
    let value = 0;
    for (let i = 0; i < count; i += 1) {
      if (this.bitCount === 0) {
        if (this.byteIndex >= this.bytes.length) throw new Error("Unexpected end of compressed playground payload");
        this.bitBuffer = this.bytes[this.byteIndex];
        this.byteIndex += 1;
        this.bitCount = 8;
      }
      value |= (this.bitBuffer & 1) << i;
      this.bitBuffer >>>= 1;
      this.bitCount -= 1;
    }
    return value;
  }

  alignToByte() {
    this.bitBuffer = 0;
    this.bitCount = 0;
  }

  readByte() {
    if (this.bitCount === 0) {
      if (this.byteIndex >= this.bytes.length) throw new Error("Unexpected end of compressed playground payload");
      const value = this.bytes[this.byteIndex];
      this.byteIndex += 1;
      return value;
    }
    return this.readBits(8);
  }

  readBytes(length) {
    this.alignToByte();
    if (this.byteIndex + length > this.bytes.length) {
      throw new Error("Unexpected end of compressed playground payload");
    }
    const chunk = this.bytes.slice(this.byteIndex, this.byteIndex + length);
    this.byteIndex += length;
    return chunk;
  }
}
